### ISSUE TITLE
Some JPEG files cause reads too far into the file - and go over the maximum reads restriction

### ISSUE THREAD

**Issue by bermannoah** [WeTransfer/format_parser#75] opened 2018-03-07 15:40 UTC
We've found a few files (mostly Photoshop-generated CMYK jpegs) that have characters that we can't read - or read incorrectly - and this can lead to mildly unbounded reads, or it'll bail with a result of `nil`. Creating an issue to track research etc.

**Comment by julik** [comment] 2018-03-24 10:46
So far it seems the issue is rather that we _can_ parse those files, but we have to read a lot of data to get to the chunks which contain dimensions.

**Comment by julik** [comment] 2018-04-10 10:32
I've upped the page size a bit, closing for now - let's see if it reemerges. Tentatively fixed in #89

**Closed by julik** 2018-04-10 10:32 UTC
Labels: bug
